import type { NextPage } from "next";
import Head from "next/head";
import { Track } from "@uniformdev/context-react";
import { IPage } from "../lib/sanity-types";
import { PageComponentsList } from "./PageComponentsList";
import { EnrichmentData } from "@uniformdev/context";

export type PageProps = {
  preview: boolean;
  page: IPage;
};

const Page: NextPage<PageProps> = ({ page }) => {
  const behaviour: EnrichmentData[] = [];
  const { components, enrichmentTag } = page || {};
  const { uniformEnrichmentTags } = enrichmentTag || {};

  if (uniformEnrichmentTags) {
    try {
      const enrichmentValue = JSON.parse(uniformEnrichmentTags);
      behaviour.push(...enrichmentValue);
    } catch (e: unknown) {
      // eslint-disable-next-line no-console
      console.error("Failed to parse enrichment tag field: ", e);
    }
  }
  return (
    <Track behavior={behaviour}>
      <Head>
        <title>Uniform Context + Sanity + NextJS</title>
        <meta
          name="description"
          content="Generated by create next app, modified with typescript, etc"
        />
      </Head>
      {components ? <PageComponentsList components={components} /> : null}
    </Track>
  );
};

export default Page;
